# IP List: We write private IPs for example. You might want to change to your own Public IPs
# you may use any number of IPs as you want
ips:
userlist: "configs/kin/kin_users.txt"
save_id: "kin"
save_dir: "data/kin_merged"
